name: GitHub Action HERON test
run-name: ${{ github.actor }} is testing out RAVEN
on: [push]
jobs:
  Test-HERON-Action:
    runs-on: self-hosted
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pwd
      